<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input punch in</name>
   <tag></tag>
   <elementGuidId>6a678a6f-fe61-4f7c-bc9b-d06e306a6aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#punch_in > #punch_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='punch_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;punch_in&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c787dfaa-5c67-4a59-9990-beac02ed31cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f984f45c-d808-4703-b4c1-ddaa3d2d2184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>punch_in</value>
      <webElementGuid>f44f2366-1f33-422e-8fd4-7a479d6eddf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99f94de6-9e0d-4319-af7f-944528913812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>punch_in</value>
      <webElementGuid>5df9656e-cd13-4d00-8b80-c37260e0d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm_attendenceapproval&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;form-row mb-2&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-6 col-sm-6 form-group&quot;]/div[@id=&quot;punch_in&quot;]/input[@id=&quot;punch_in&quot;]</value>
      <webElementGuid>7ef6d16f-008f-4a15-8637-a41dafc70056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='punch_in']</value>
      <webElementGuid>c3a75717-418d-4c6f-9c24-e9e41fcebab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='punch_in']/input</value>
      <webElementGuid>ca750065-ee05-44a2-a6f0-94f6b84d7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>feb82d4f-d52e-467d-a202-e43774b4b928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'punch_in' and @type = 'text' and @id = 'punch_in']</value>
      <webElementGuid>c8955ecb-1ebe-4e98-b385-89574f48017a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
