<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input punch out</name>
   <tag></tag>
   <elementGuidId>e1ebb7f9-f5b3-43a6-80c1-0717eae85c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#punch_out > #punch_out</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='punch_out']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;punch_out&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a07c8ed3-2da1-44a3-908d-fdec77438adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b96acecc-cd6a-43cf-ae30-e4e93a28ba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>punch_out</value>
      <webElementGuid>73168fe7-009c-434d-8f36-9a128094a7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3d39ba1-aac4-453f-b33a-de15f37f4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>punch_out</value>
      <webElementGuid>339a9559-3341-4348-91b4-51fe8fe25fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm_attendenceapproval&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;form-row mb-2&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-6 col-sm-6 form-group&quot;]/div[@id=&quot;punch_out&quot;]/input[@id=&quot;punch_out&quot;]</value>
      <webElementGuid>aae75a0d-e785-4e99-b58b-45e89a890928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='punch_out']</value>
      <webElementGuid>0d824c25-1703-4305-a7d2-0962435c46c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='punch_out']/input</value>
      <webElementGuid>9bffd754-507a-4f34-b0fc-9cea19128afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>29f70d55-f2bf-4da2-8e7e-005a033c3125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'punch_out' and @type = 'text' and @id = 'punch_out']</value>
      <webElementGuid>eee92965-b3c2-4277-a5b1-0657f35c7cdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
