<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yes button modal popup</name>
   <tag></tag>
   <elementGuidId>551d0264-06c0-4eb0-9b1a-4e6d7b1a3e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#926de4e0-df86-4fce-b1ae-d5555f6c1950</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='926de4e0-df86-4fce-b1ae-d5555f6c1950']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Yes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e06fb3c8-b1c0-427b-bf53-ded5357a9664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary bootstrap4-dialog-button</value>
      <webElementGuid>53134ace-1bb9-4aa0-8068-ac8169fff3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>926de4e0-df86-4fce-b1ae-d5555f6c1950</value>
      <webElementGuid>38253668-626e-4de3-b4e7-df714fa2aedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>a6d842de-67dc-4754-b186-1bac551eec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;926de4e0-df86-4fce-b1ae-d5555f6c1950&quot;)</value>
      <webElementGuid>83cbb1e7-5613-43c6-ac23-747594abf664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='926de4e0-df86-4fce-b1ae-d5555f6c1950']</value>
      <webElementGuid>47345ba5-e26e-4a1a-bb48-24a04a952ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='331b649e-8654-497d-ae62-5cf091f883f7']/div/div/div[3]/button[2]</value>
      <webElementGuid>1fc33b02-58bb-40e5-99d8-22b49936001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[1]</value>
      <webElementGuid>072c41f6-9914-45e6-947b-fd9588bff98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please confirm that entered time is in 24-hours format'])[1]/following::button[2]</value>
      <webElementGuid>1d497aa7-39d1-4f7b-bb06-18a567720499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>0eb03b43-0d79-4bd6-be19-9c2d1a859e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>e9b2338c-c433-4abf-a198-51b32f95b142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '926de4e0-df86-4fce-b1ae-d5555f6c1950' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>974a023d-f616-435a-8d53-33f63615094f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
